package play_sounds;


import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Julian
 */
public class Buttons extends javax.swing.JFrame {

    private volatile boolean threadRunning = false; 
    
    int[][] s;
    int status = 1;
    Random rnd = new Random();
    
    public int[][] createSegments()
    {
        int[][] temp={
        {1,4,3,4,5},
        {6,7,8,7,6,5},
        {8,7,6,5,4,6,7,8},
        {1,4,5,5,7,6,7,5},
        {7,8,8,7,6,5,4,5,6,7,5,4,4,3,4,5,3,1},
        {1,6,7,8,7,8,6,5},
        {7,6,8,7,6,5,4,6,7,8},
        {8,7,6,5,4,3,2,1},
        {1,2,3,4,5},
        {4,5,5,5}
    };
        return temp;
    }
    public Buttons() {
        initComponents();
    }

    public void playSegment(int index)
    {
        int dir = rnd.nextInt(2);
        if (dir==0)
            for (int i=0;i<s[index].length;i++)
            {
                String str=s[index][i]+"1.wav";
                PlaySound(new File(str));
            }
        else
            for (int i=s[index].length-1;i>=0;i--)
            {
                String str=s[index][i]+"1.wav";
                PlaySound(new File(str));
            }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Note1 = new javax.swing.JButton();
        Note2 = new javax.swing.JButton();
        Note3 = new javax.swing.JButton();
        Note4 = new javax.swing.JButton();
        Note5 = new javax.swing.JButton();
        Note7 = new javax.swing.JButton();
        Note8 = new javax.swing.JButton();
        Note6 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Note1.setText("Note 1");
        Note1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note1ActionPerformed(evt);
            }
        });

        Note2.setText("Note 2");
        Note2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note2ActionPerformed(evt);
            }
        });

        Note3.setText("Note 3");
        Note3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note3ActionPerformed(evt);
            }
        });

        Note4.setText("Note 4");
        Note4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note4ActionPerformed(evt);
            }
        });

        Note5.setText("Note 5");
        Note5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note5ActionPerformed(evt);
            }
        });

        Note7.setText("Note 7");
        Note7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note7ActionPerformed(evt);
            }
        });

        Note8.setText("Note 8");
        Note8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note8ActionPerformed(evt);
            }
        });

        Note6.setText("Note 6");
        Note6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note6ActionPerformed(evt);
            }
        });

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Note1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Note2)
                        .addGap(18, 18, 18)
                        .addComponent(Note3)
                        .addGap(18, 18, 18)
                        .addComponent(Note4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Note5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Note6)
                        .addGap(18, 18, 18)
                        .addComponent(Note7)
                        .addGap(18, 18, 18)
                        .addComponent(Note8)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Note1)
                    .addComponent(Note2)
                    .addComponent(Note3)
                    .addComponent(Note4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Note5)
                    .addComponent(Note6)
                    .addComponent(Note7)
                    .addComponent(Note8))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnStop))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Note1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note1ActionPerformed
     File Note = new File("11.WAV");    //D
       PlaySound(Note);
  
    }//GEN-LAST:event_Note1ActionPerformed

    private void Note2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note2ActionPerformed
      File Note = new File("21.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note2ActionPerformed

    private void Note3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note3ActionPerformed
       File Note = new File("31.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note3ActionPerformed

    private void Note4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note4ActionPerformed
        File Note = new File("41.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note4ActionPerformed

    private void Note5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note5ActionPerformed
     File Note = new File("51.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note5ActionPerformed

    private void Note7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note7ActionPerformed
       File Note = new File("71.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note7ActionPerformed

    private void Note8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note8ActionPerformed
      File Note = new File("81.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note8ActionPerformed

    private void Note6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note6ActionPerformed
        File Note = new File("61.WAV");
       PlaySound(Note);
    }//GEN-LAST:event_Note6ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        s=createSegments();
        startThread();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        status = 1 - status;
        threadRunning = false;
    }//GEN-LAST:event_btnStopActionPerformed

 public void startThread(){
  Thread t = new Thread(new Runnable(){
      @Override
      public void run(){
          threadRunning = true;
          while(threadRunning){
              playSegment(rnd.nextInt(s.length));
          }
      }
  });
  t.start();
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buttons().setVisible(true);
            }
        });
    }
     public void PlaySound(File Sound)
    {
        int delay;
        try{
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(Sound));
            clip.start();
            delay=rnd.nextInt(4000);
            Thread.sleep(clip.getMicrosecondLength()/(1000+delay));    
        }catch(LineUnavailableException | UnsupportedAudioFileException | IOException | InterruptedException e){
            
        }         
                    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Note1;
    private javax.swing.JButton Note2;
    private javax.swing.JButton Note3;
    private javax.swing.JButton Note4;
    private javax.swing.JButton Note5;
    private javax.swing.JButton Note6;
    private javax.swing.JButton Note7;
    private javax.swing.JButton Note8;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables
}
